%% super detailed
M_.shock_groups.Joao.group1.label = 'TFP EA';
M_.shock_groups.Joao.group1.shocks = { 'EPS_LAYTREND_EA' 'EPS_GAYTREND_EA' 'EPS_AY_EA'};
M_.shock_groups.Joao.group2.label = 'Gov. consumption EA';
M_.shock_groups.Joao.group2.shocks = { 'EPS_G_EA'};
M_.shock_groups.Joao.group3.label = 'Gov. investment EA';
M_.shock_groups.Joao.group3.shocks = { 'EPS_IG_EA'};
M_.shock_groups.Joao.group4.label = 'Transfers EA';
M_.shock_groups.Joao.group4.shocks = {'EPS_T_EA' };
M_.shock_groups.Joao.group5.label = 'Taxes EA';
M_.shock_groups.Joao.group5.shocks = { 'EPS_TAX_EA'};
M_.shock_groups.Joao.group6.label = 'Consumption-specific productivity EA';
M_.shock_groups.Joao.group6.shocks = { 'EPS_APC_EA' };
M_.shock_groups.Joao.group7.label = 'Monetary EA';
M_.shock_groups.Joao.group7.shocks = { 'EPS_INOM_EA'};
M_.shock_groups.Joao.group8.label = 'Price Mark-up EA';
M_.shock_groups.Joao.group8.shocks = { 'EPS_MUY_EA'};
M_.shock_groups.Joao.group9.label = 'Bond premium EA';
M_.shock_groups.Joao.group9.shocks = { 'EPS_BW_EA'};
M_.shock_groups.Joao.group10.label = 'Private savings shock EA';
M_.shock_groups.Joao.group10.shocks = { 'EPS_UC_EA'};
M_.shock_groups.Joao.group11.label = 'Investment risk premium EA';
M_.shock_groups.Joao.group11.shocks = { 'EPS_S_EA_EA'};
M_.shock_groups.Joao.group12.label = 'Wage Mark-up EA';
M_.shock_groups.Joao.group12.shocks = { 'EPS_U_EA'};
M_.shock_groups.Joao.group13.label = 'Labor cost shock EA';
M_.shock_groups.Joao.group13.shocks = { 'EPS_CU_EA' 'EPS_ND_EA'};
M_.shock_groups.Joao.group14.label = 'Other shocks EA';
M_.shock_groups.Joao.group14.shocks = { 'EPS_B_EA_EA' 'EPS_APG_EA' 'EPS_API_EA' 'EPS_APIG_EA' 'EPS_POP_EA' 'EPS_ACTR_EA'};
M_.shock_groups.Joao.group15.label = 'Export price EA';
M_.shock_groups.Joao.group15.shocks = { 'EPS_PX_EA'};
M_.shock_groups.Joao.group16.label = 'Bilateral export price EA RoW';
M_.shock_groups.Joao.group16.shocks = { 'EPS_PX_EA_RoW'};
M_.shock_groups.Joao.group17.label = 'Import demand EA';
M_.shock_groups.Joao.group17.shocks = {'EPS_M_EA'};
M_.shock_groups.Joao.group18.label = 'Import demand RoW';
M_.shock_groups.Joao.group18.shocks = {'EPS_M_RoW'};
M_.shock_groups.Joao.group19.label = 'Aggregate demand RoW';
M_.shock_groups.Joao.group19.shocks = { 'EPS_UC_RoW' };
M_.shock_groups.Joao.group20.label = 'Supply RoW';
M_.shock_groups.Joao.group20.shocks = { 'EPS_Y_RoW' 'EPS_GAYTREND_RoW' 'EPS_LAYTREND_RoW' 'EPS_GAY0_RoW'};
M_.shock_groups.Joao.group21.label = 'Monetary RoW';
M_.shock_groups.Joao.group21.shocks = { 'EPS_INOM_RoW'};
M_.shock_groups.Joao.group22.label = 'Commodities demand';
M_.shock_groups.Joao.group22.shocks = { 'EPS_OIL_EA'};
M_.shock_groups.Joao.group23.label = 'Oil';
M_.shock_groups.Joao.group23.shocks = { 'EPS_GAPBRENTTREND_RoW'};
M_.shock_groups.Joao.group24.label = 'Non Oil';
M_.shock_groups.Joao.group24.shocks = { 'EPS_GAPXCOMMTREND_RoW' 'EPS_POIL_EA_RoW'};
M_.shock_groups.Joao.group25.label = 'Flight to safety';
M_.shock_groups.Joao.group25.shocks = { 'EPS_FQ_EA'};
M_.shock_groups.Joao.group26.label = 'Inventories';
M_.shock_groups.Joao.group26.shocks = { 'EPS_INV_EA'};

%%
options_ = set_default_plot_shock_decomposition_options(options_);
options_.plot_shock_decomp.interactive = 1;
options_.plot_shock_decomp.nodisplay = 1;
options_.plot_shock_decomp.steadystate = 1;
options_.plot_shock_decomp.write_xls = 1;
options_.plot_shock_decomp.type = 'yoy';
options_.plot_shock_decomp.use_shock_groups = 'Joao';
options_.plot_shock_decomp.graph_format = char('fig','eps');
var_list_ = char('GYOBS_EA');
plot_shock_decomposition(M_, oo_, options_, var_list_);

%%
options_ = set_default_plot_shock_decomposition_options(options_);
options_.plot_shock_decomp.interactive = 1;
options_.plot_shock_decomp.nodisplay = 1;
options_.plot_shock_decomp.steadystate = 1;
options_.plot_shock_decomp.write_xls = 1;
options_.plot_shock_decomp.type = 'qoq';
options_.plot_shock_decomp.use_shock_groups = 'Joao';
options_.plot_shock_decomp.graph_format = char('fig','eps');
var_list_ = char('GYOBS_EA','GC_EA','GI_EA');
plot_shock_decomposition(M_, oo_, options_, var_list_);
%%
options_ = set_default_plot_shock_decomposition_options(options_);
options_.plot_shock_decomp.interactive = 1;
options_.plot_shock_decomp.nodisplay = 1;
options_.plot_shock_decomp.steadystate = 1;
options_.plot_shock_decomp.write_xls = 1;
options_.plot_shock_decomp.type = 'aoa';
options_.plot_shock_decomp.use_shock_groups = 'Joao';
options_.plot_shock_decomp.graph_format = char('fig','eps');
var_list_ = char('LYOBS_EA');
plot_shock_decomposition(M_, oo_, options_, var_list_);
