function print_latex_notation()

global M_

filename = [M_.fname '_notation.TeX'];
fidTeX = fopen(filename,'w+');
fprintf(fidTeX,'%% TeX-table generated by print_latex_notation (Dynare).\n');
fprintf(fidTeX,'%% NOTATION for LATEX dynare \n');
fprintf(fidTeX,['%% ' datestr(now,0)]);
fprintf(fidTeX,' \n');
fprintf(fidTeX,' \n');
fprintf(fidTeX,'\\begin{center}\n');
fprintf(fidTeX,'\\begin{longtable}{l|l|l|c} \n');
fprintf(fidTeX,'\\caption{Notation (parameter names)} \\\\ \n ');
fprintf(fidTeX,'\\label{Table:Notation:1}\\\\\n');
fprintf(fidTeX,'\\hline\\hline \\\\ \n');
fprintf(fidTeX,'DYNARE  & LaTeX & Notes & value \\\\ \n');
fprintf(fidTeX,'\\hline \\endfirsthead \n');
fprintf(fidTeX,'\\caption{(continued)}\n ');
fprintf(fidTeX,'\\label{Table:Notation:1}\\\\\n');
fprintf(fidTeX,'\\hline\\hline \\\\ \n');
fprintf(fidTeX,'DYNARE  & LaTeX & Notes & value \\\\ \n');
fprintf(fidTeX,'\\hline \\endhead \n');
fprintf(fidTeX,'\\hline \\multicolumn{4}{r}{(Continued on next page)} \\\\ \\hline \\endfoot \n');
fprintf(fidTeX,'\\hline \\hline \\endlastfoot \n');
for i=1:M_.param_nbr,
    fprintf(fidTeX,'\\verb|%s| & $%s$ & & %8.4f \\\\ \n',...
        deblank(M_.param_names(i,:)), ...
        M_.param_names_tex(i,:), ...
        M_.params(i));
end
fprintf(fidTeX,'\\end{longtable}\n ');
fprintf(fidTeX,'\\end{center}\n');


fprintf(fidTeX,' \n');
fprintf(fidTeX,'\\begin{center}\n');
fprintf(fidTeX,'\\begin{longtable}{l|l|l|c} \n');
fprintf(fidTeX,'\\caption{Notation (endogenous variables)} \\\\ \n ');
fprintf(fidTeX,'\\label{Table:Notation:2}\\\\\n');
fprintf(fidTeX,'\\hline\\hline \\\\ \n');
fprintf(fidTeX,'DYNARE  & LaTeX & Notes & st. state \\\\ \n');
fprintf(fidTeX,'\\hline \\endfirsthead \n');
fprintf(fidTeX,'\\caption{(continued)}\n ');
fprintf(fidTeX,'\\label{Table:Notation:2}\\\\\n');
fprintf(fidTeX,'\\hline\\hline \\\\ \n');
fprintf(fidTeX,'DYNARE  & LaTeX & Notes & st. state \\\\ \n');
fprintf(fidTeX,'\\hline \\endhead \n');
fprintf(fidTeX,'\\hline \\multicolumn{4}{r}{(Continued on next page)} \\\\ \\hline \\endfoot \n');
fprintf(fidTeX,'\\hline \\hline \\endlastfoot \n');
for i=1:M_.endo_nbr,
    fprintf(fidTeX,'\\verb|%s| & $%s$ & & %8.4f \\\\ \n',...
        deblank(M_.endo_names(i,:)), ...
        M_.endo_names_tex(i,:), ...
        get_mean(deblank(M_.endo_names(i,:))));
end
fprintf(fidTeX,'\\end{longtable}\n ');
fprintf(fidTeX,'\\end{center}\n');


fprintf(fidTeX,' \n');
fprintf(fidTeX,'\\begin{center}\n');
fprintf(fidTeX,'\\begin{longtable}{l|l|l} \n');
fprintf(fidTeX,'\\caption{Notation (exogenous shocks)} \\\\ \n ');
fprintf(fidTeX,'\\label{Table:Notation:3}\\\\\n');
fprintf(fidTeX,'\\hline\\hline \\\\ \n');
fprintf(fidTeX,'DYNARE  & LaTeX & Notes \\\\ \n');
fprintf(fidTeX,'\\hline \\endfirsthead \n');
fprintf(fidTeX,'\\caption{(continued)}\n ');
fprintf(fidTeX,'\\label{Table:Notation:3}\\\\\n');
fprintf(fidTeX,'\\hline\\hline \\\\ \n');
fprintf(fidTeX,'DYNARE  & LaTeX & Notes \\\\ \n');
fprintf(fidTeX,'\\hline \\endhead \n');
fprintf(fidTeX,'\\hline \\multicolumn{3}{r}{(Continued on next page)} \\\\ \\hline \\endfoot \n');
fprintf(fidTeX,'\\hline \\hline \\endlastfoot \n');
for i=1:M_.exo_nbr,
    fprintf(fidTeX,'\\verb|%s| & $%s$ & \\\\ \n',...
        deblank(M_.exo_names(i,:)), ...
        M_.exo_names_tex(i,:));
end
fprintf(fidTeX,'\\end{longtable}\n ');
fprintf(fidTeX,'\\end{center}\n');

fprintf(fidTeX,'%% End of TeX file.\n');
fclose(fidTeX);
